dist: trusty
sudo: required

addons:
  chrome: stable
language: node_js
node_js:
  - '8'
before_install:
  - npm install -g npm@latest
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
jobs:
  include:
    - stage: test
      name: 'app-i18n'
      script:
        - cd angular/app-i18n && npm i && npm run test:ci
    - stage: test
      name: 'app-settings'
      script:
        - cd angular/app-settings && npm i && npm run test:ci
    - stage: test
      name: 'basic-components'
      script:
        - cd angular/components/basic-components && npm i && npm run test:ci
