# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    displayName: 'angular/app-i18n: install dependencies'
    inputs:
      command: 'install'
      workingDir: './angular/app-i18n'

  - task: Npm@1
    displayName: 'angular/app-i18n: run unit tests'
    inputs:
      command: 'custom'
      customCommand: 'run test:ci'
      workingDir: './angular/app-i18n'

  - task: Npm@1
    displayName: 'angular/app-settings: install dependencies'
    inputs:
      command: 'install'
      workingDir: './angular/app-settings'

  - task: Npm@1
    displayName: 'angular/app-settings: run unit tests'
    inputs:
      command: 'custom'
      customCommand: 'run test:ci'
      workingDir: './angular/app-settings'
